micronaut:
  application:
    name: micronaut-zeebe-client-example
  server:
    port: 8087
netty:
  default:
    allocator:
      max-order: 3
zeebe:
  client:
    cloud:
      defaultJobWorkerName: novatec-worker
